### ISSUE TITLE
Add Mocked Tests: Volume Actions

### ISSUE THREAD

**Issue by danaelhe** [digitalocean/pydo#203]
**Overview**
Add more test coverage for Pydo, specifically for Volume Actions.

[Mocked Tests: tests/mocked/](https://github.com/digitalocean/pydo#mocked-tests-testsmocked)
Tests in the mocked directory include:
- Tests that validate the generated client has all the expected classes and methods for the respective API resources and operations.
- Tests that exercise individual operations against mocked responses.

_These tests do not act against the real API so no real resources are created._

To run mocked tests, run:

`make test-mocked`

**Instructions**
1. Clone this repo.
2. If you haven't already, install Python (version: >= 3.7.2) through their [official installer](https://www.python.org/downloads/).
3. CD into the directory and run `make install` 
4. View file: [tests/mocked/test_block_storage.py](https://github.com/digitalocean/pydo/tree/main/tests)
5. Add tests for `volume_actions.get`, `volume_actions.list`,  `volume_actions.post`, `volume_actions.post_by_id`
6. API documentation is [here](https://docs.digitalocean.com/reference/api/api-reference/#tag/Block-Storage-Actions)
7. Pydo Documentation is [here](https://pydo.readthedocs.io/en/latest/#pydo.operations.VolumeActionsOperations)

**Comment by shivam-Purohit** [comment]
hey @danaelhe can I look into this?

**Comment by danaelhe** [comment]
> hey @danaelhe can I look into this?

Absolutely 😄 Thanks!
