### ISSUE TITLE
Add Mocked Tests: Droplets (part 1)

### ISSUE THREAD

**Issue by danaelhe** [digitalocean/pydo#208]
Overview
Add more test coverage for Pydo, specifically for droplets

[Mocked Tests: tests/mocked/](https://github.com/digitalocean/pydo#mocked-tests-testsmocked)
Tests in the mocked directory include:
- Tests that validate the generated client has all the expected classes and methods for the respective API resources and operations.
- Tests that exercise individual operations against mocked responses.

_These tests do not act against the real API so no real resources are created._

To run mocked tests, run:

`make test-mocked`

Instructions
1. Clone this repo.
2. If you haven't already, install Python (version: >= 3.7.2) through their [official installer](https://www.python.org/downloads/).
3. CD into the directory and run make install
4. View file: [tests/mocked/test_droplets.py](https://github.com/digitalocean/pydo/blob/main/tests/mocked/test_droplets.py)
5. Add tests for `droplets.destroy_by_tag`, `droplets.list_backups`, `droplets.list_snapshots`, `droplets.list_kernels`, `droplets.list_firewalls`, `droplets.list_neighbors`, `databases.list_associated_resources`
6. API documentation is [here](https://docs.digitalocean.com/reference/api/api-reference/#tag/Droplets)
7. Pydo Documentation is [here](https://pydo.readthedocs.io/en/latest/#pydo.operations.DropletsOperations)

**Comment by work-mohit** [comment]
Started working on this!

**Comment by danaelhe** [comment]
Addressed in #225 and #223
