### ISSUE TITLE
Add Mocked Tests: Functions

### ISSUE THREAD

**Issue by danaelhe** [digitalocean/pydo#210]
**Overview**
Add more test coverage for Pydo, specifically for Functions

[Mocked Tests: tests/mocked/](https://github.com/digitalocean/pydo#mocked-tests-testsmocked)
Tests in the mocked directory include:
- Tests that validate the generated client has all the expected classes and methods for the respective API resources and operations.
- Tests that exercise individual operations against mocked responses.

_These tests do not act against the real API so no real resources are created._

To run mocked tests, run:

`make test-mocked`

**Instructions**
1. Clone this repo.
2. If you haven't already, install Python (version: >= 3.7.2) through their [official installer](https://www.python.org/downloads/).
3. CD into the directory and run make install
4. Create file: tests/mocked/test_functions.py
5. Add tests for `functions.create_namespace`, `functions.create_trigger`, `functions.delete_namespace`, `functions.delete_trigger`, `functions.get_namespace`, `functions.get_trigger`,  `functions.list_namespaces`, `functions.list_triggers`, `functions.update_trigger`
6. API documentation is [here](https://docs.digitalocean.com/reference/api/api-reference/#tag/Functions)
7. Pydo Documentation is [here](https://pydo.readthedocs.io/en/latest/#pydo.operations.FunctionsOperations)

**Comment by PalaniappanC** [comment]
Hi @danaelhe I would like to work on this. Kindly assign this to my name

**Comment by work-mohit** [comment]
@PalaniappanC  you can start working and make a PR :)

**Comment by giftcup** [comment]
I've started working on this.
