### ISSUE TITLE
Add Mocked Tests: Uptime (part 1)

### ISSUE THREAD

**Issue by danaelhe** [digitalocean/pydo#212]
**Overview**
Add more test coverage for Pydo, specifically for Uptime

[Mocked Tests: tests/mocked/](https://github.com/digitalocean/pydo#mocked-tests-testsmocked)
Tests in the mocked directory include:
- Tests that validate the generated client has all the expected classes and methods for the respective API resources and operations.
- Tests that exercise individual operations against mocked responses.

_These tests do not act against the real API so no real resources are created._

To run mocked tests, run:

`make test-mocked`

**Instructions**
1. Clone this repo.
2. If you haven't already, install Python (version: >= 3.7.2) through their [official installer](https://www.python.org/downloads/).
3. CD into the directory and run make install
4. Create file: tests/mocked/test_uptime.py
5. Add tests for `uptime.create_alert`, `uptime.create_check`, `uptime.delete_alert`, `uptime.delete_check`, `uptime.get_alert`, `uptime.get_check`
6. API documentation is [here](https://docs.digitalocean.com/reference/api/api-reference/#tag/Uptime)
7. Pydo Documentation is [here](https://pydo.readthedocs.io/en/latest/#pydo.operations.UptimeOperations)

**Comment by dhananjay0610** [comment]
started working on this

**Comment by work-mohit** [comment]
@danaelhe you can close this issue.  completed in #219

**Comment by danaelhe** [comment]
> @danaelhe you can close this issue. completed in #219

PR #219 closes Github Issue #213 ! This one's still free.

**Comment by giftcup** [comment]
I've started working on this.
