### ISSUE TITLE
Create `make precommit` command

### ISSUE THREAD

**Issue by danaelhe** [digitalocean/pydo#220]
**Issue**
The CI/CD pipeline includes a linter test that must pass. It would be much easier if we baked `poetry run black tests` into a `make precommit` command in order for the `black` package to reformat the files before passing them through the CI/CD linter.

**Comment by work-mohit** [comment]
started working on this!

**Comment by work-mohit** [comment]
@danaelhe I think we don't have to make a command for this. pre-commit are hooks that invoke specified operations before committing automatically.

**Comment by shivam-Purohit** [comment]
one way is to map the pre-commit to a script and run these and other commands you like before the commit.

**Comment by work-mohit** [comment]
If anyone feels like raising a PR, they can do it. From my side, it can take some time to complete.

**Comment by shivam-Purohit** [comment]
@danaelhe can you please explain more about the `make precommit` command? I am not sure about the approach to the problem.
I was thinking of making a precommit.yml file using the pre-commit package and adding the steps that will run before a git commit.  This can be done using the[ pre-commit ](https://pre-commit.com/) package. A script can also be used for the same using the[ pre-commit hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) provided by github. Where we can add custom scripts to run before any commit for example some tests and necessary commands.
What do you think?

**Comment by shivam-Purohit** [comment]
Working with the first approach!

**Comment by danaelhe** [comment]
resolved in #228
