### ISSUE TITLE
Documentation: get env

### ISSUE THREAD

**Issue by KylePeterDavies** [digitalocean/pydo#277]
In the README.md to get the DigitalOcean Token you suggest... 

```python
token=os.getenv("$DIGITALOCEAN_TOKEN")
```

I believe you meant

```python
token=os.getenv("DIGITALOCEAN_TOKEN")
```

Also in "Use the interactive python shell"

```python
...
>>> c.droplets.get()
```

I think you mean the list method as get takes a droplet_id

```python
...
>>> c.droplets.list()
```

**Comment by KylePeterDavies** [comment]
Please see: https://github.com/digitalocean/pydo/pull/278

**Comment by andrewsomething** [comment]
Closed via https://github.com/digitalocean/pydo/pull/278 Thanks again @KylePeterDavies!
