### ISSUE TITLE
Add mocked tests: update database user

### ISSUE THREAD

**Issue by loosla** [digitalocean/pydo#341]
#### Overview
Enhance test coverage by adding mocked test for the function that updates database user.

Mocked tests do not act against the real API so no real resources are created.

To run mocked tests, run: `make test-mocked`
#### Instructions 

1. Clone this repo.
2. If you haven't already, install Python (version: >= 3.7.2) through their [official installer](https://www.python.org/downloads/).
3. CD into the directory and run `make install`
4. Open file: tests/mocked/test_databases.py
5. Add a mocked test for databases.update_user (you can use `test_databases_get_user` for reference)
6. API documentation: [update_user](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_update_user)

**Comment by AdithyaPadmashali** [comment]
Could you assign this to me?

**Comment by gagan-bhullar-tech** [comment]
@loosla can you please review PR.
