### ISSUE TITLE
Add mocked tests: get  and update database clusters metrics endpoint credentials

### ISSUE THREAD

**Issue by loosla** [digitalocean/pydo#342]
#### Overview
Enhance test coverage by adding mocked test for the function that gets and updates database clusters metrics endpoint credentials.

Mocked tests do not act against the real API so no real resources are created.

To run mocked tests, run: `make test-mocked`
#### Instructions 

1. Clone this repo.
2. If you haven't already, install Python (version: >= 3.7.2) through their [official installer](https://www.python.org/downloads/).
3. CD into the directory and run `make install`
4. Open file: tests/mocked/test_databases.py
5. Add a mocked test for databases.get_cluster_metrics_credentials, databases.update_cluster_metrics_credentials
6. API documentation: [get_cluster_metrics_credentials](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_get_cluster_metrics_credentials), [update_cluster_metrics_credentials](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_update_cluster_metrics_credentials)

**Comment by AryanBakliwal** [comment]
Hey @loosla, I've started working on this please assign me
