### ISSUE TITLE
Add mocked tests: install_update

### ISSUE THREAD

**Issue by loosla** [digitalocean/pydo#344]
#### Overview
Enhance test coverage by adding mocked test for the function that starts database maintenance - `install_update`.

Mocked tests do not act against the real API so no real resources are created.

To run mocked tests, run: `make test-mocked`
#### Instructions 

1. Clone this repo.
2. If you haven't already, install Python (version: >= 3.7.2) through their [official installer](https://www.python.org/downloads/).
3. CD into the directory and run `make install`
4. Open file: tests/mocked/test_databases.py
5. Add a mocked test with the name `test_databases_install_update` for databases.install_update. 

Note: The function implementation can be found in src/pydo/operations/_operations.py.

**Comment by gagan-bhullar-tech** [comment]
@loosla thanks. Created PR. Please review and assign to me.
