### ISSUE TITLE
Add mocked tests: get_backup_policy

### ISSUE THREAD

**Issue by loosla** [digitalocean/pydo#345]
#### Overview
Enhance test coverage by adding mocked test for the function that retrieves the backup policy for an existing droplet - `get_backup_policy`.

Mocked tests do not act against the real API so no real resources are created.

To run mocked tests, run: `make test-mocked`
#### Instructions 

1. Clone this repo.
2. If you haven't already, install Python (version: >= 3.7.2) through their [official installer](https://www.python.org/downloads/).
3. CD into the directory and run `make install`
4. Open file: tests/mocked/test_droplets.py
5. Add a mocked test with the name `test_get_backup_policy` for droplets.get_backup_policy. 

Note: The function implementation can be found in src/pydo/operations/_operations.py.

**Comment by gagan-bhullar-tech** [comment]
@loosla get_backup_policy method is in DropletOperations. I think we need to add test case in test_droplets.py. Can you please confirm. Also, please assign it to me.

**Comment by loosla** [comment]
Thank you for catching that! I’ve updated the description.

**Comment by gagan-bhullar-tech** [comment]
@loosla thanks. Created PR. Please review.
