### ISSUE TITLE
Add mocked tests: list_backup_policies

### ISSUE THREAD

**Issue by loosla** [digitalocean/pydo#346]
#### Overview
Enhance test coverage by adding mocked test for the function that lists backup policies for all existing droplets - `list_backup_policies`.

Mocked tests do not act against the real API so no real resources are created.

To run mocked tests, run: `make test-mocked`
#### Instructions 

1. Clone this repo.
2. If you haven't already, install Python (version: >= 3.7.2) through their [official installer](https://www.python.org/downloads/).
3. CD into the directory and run `make install`
4. Open file: tests/mocked/test_droplets.py
5. Add a mocked test with the name `test_list_backup_policies` for droplets.list_backup_policies. 

Note: The function implementation can be found in src/pydo/operations/_operations.py.

**Comment by eleensmathew** [comment]
Can I work on this ?

**Comment by gagan-bhullar-tech** [comment]
@loosla list_backup_policies method is in DropletOperations. I think we need to add test case in test_droplets.py. Can you please confirm.

**Comment by loosla** [comment]
@gagan-bhullar-tech Thank you for catching that! I’ve updated the description. :+1:

**Comment by loosla** [comment]
I appreciate everyone's interest in contributing! Just a friendly reminder: when we assign someone to a PR in an open repository, it can sometimes limit opportunities for other developers to contribute, it may lead to issues being abandoned and work not progressing. 

We generally would like to follow a first-come, first-served approach for assignments to ensure fairness.

I recommend leaving a comment to let others know you've started working on this issue, along with an approximate timeline for when you expect to finish. This way, everyone will be aware that you're handling it.

Thank you for your understanding! :ocean:  :dolphin: :ocean:
