### ISSUE TITLE
Add mocked tests: list_supported_backup_policies

### ISSUE THREAD

**Issue by loosla** [digitalocean/pydo#347]
#### Overview
Enhance test coverage by adding mocked test for the function that lists supported droplet backup policies - `list_supported_backup_policies`.

Mocked tests do not act against the real API so no real resources are created.

To run mocked tests, run: `make test-mocked`
#### Instructions 

1. Clone this repo.
2. If you haven't already, install Python (version: >= 3.7.2) through their [official installer](https://www.python.org/downloads/).
3. CD into the directory and run `make install`
4. Open file: tests/mocked/test_droplets.py
5. Add a mocked test with the name `test_list_supported_backup_policies` for droplets.list_supported_backup_policies. 

Note: The function implementation can be found in src/pydo/operations/_operations.py.

**Comment by gagan-bhullar-tech** [comment]
@loosla list_supported_backup_policies method is for droplets. I think we need to add test case in test_droplets.py. Can you please confirm.

**Comment by loosla** [comment]
Thank you for catching that! I’ve updated the description.
